name: Android CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Get current date
        id: get-date
        run: echo "CURRENT_DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV

      - name: Build with Gradle
        run: ./gradlew assembleRelease

      - name: Rename APK
        run: |
          APK_PATH="app/build/outputs/apk/release/app-release.apk"
          NEW_APK_NAME="DT_${CURRENT_DATE}_2.1.0.apk"
          mv $APK_PATH "app/build/outputs/apk/release/$NEW_APK_NAME"

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: app/build/outputs/apk/release/DT_${CURRENT_DATE}_2.1.0.apk
